version: '3'

services:
  todolist:
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: production
      PORT: 8080
    depends_on:
      - postgres
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: 'kenlammmm/api-server:latest'
    ports:
      - '8080:8080'
  postgres:
    image: 'postgres:13'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data

      # POSTGRES_USER: postgres
      # POSTGRES_PASSWORD: postgres
      # POSTGRES_DB: todolist
      # POSTGRES_HOST: postgres